name: run

on:
  push:
    branches-ignore:
      - "master"
      - "main"

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Check types
        run: yarn tsc --noEmit
