name: run

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1-5'

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run app
        run: yarn start
        env:
          MERGE_DEPENDABOT__TOKEN: ${{ secrets.MERGE_DEPENDABOT__TOKEN }}
          MERGE_DEPENDABOT__MAX_ATTEMPTS: 3
